version: "3"
services:
  api:
    build: .
    ports:
      - 3000:3000
    command: flask run --host=0.0.0.0 --port=3000 --reload --debugger
    networks:
      - insta_clone
    container_name: api
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5433:5432
    env:
      - .env
    container_name: postgres
    networks:
      - insta_clone

networks:
  insta_clone: