version: "3"
services:
  api:
    build: .
    ports:
      - 3000:3000
    command: flask run --host=192.168.29.84  --port=3000 --reload --debugger
    networks:
      - insta_clone
    container_name: api
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=insta_clone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yash
    container_name: postgres
    restart: unless-stopped
    networks:
      - insta_clone

networks:
  insta_clone:
